config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: 'questions#index'

  concern :votable do
    member do
      post :vote
      delete :unvote
    end
  end

  concern :commentable do
    member do
      post :create_comment
    end
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, shallow: true, except: :index, concerns: [:votable, :commentable]
    resources :question_subscriptions, only: [:create, :destroy], shallow: true
  end

post 'search', action: :create, controller: 'search'
get 'search', action: :show, controller: 'search'

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :comments, only: :destroy
  resources :users, only: :show

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, only: [:index, :show, :create, :update, :destroy], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :best_answer, class_name: 'Answer', optional: true
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :award, dependent: :destroy
  has_many :question_subscriptions, dependent: :destroy
  has_many :subscribers, through: :question_subscriptions, source: :user

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :reject_links, allow_destroy: true
  accepts_nested_attributes_for :award, reject_if: :all_blank, allow_destroy: true

  validates :title, :body, presence: true

  def reject_links(attributes)
    attributes[:name].blank? && attributes[:url].blank?
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  authorize_resource

  def index
    @questions = Question.all
    render json: @questions
  end

  def show
    render json: @question
  end

  def create
    @question = current_resource_owner.questions.new(question_params)
    if @question.save
      render json: @question
    else
      render json: {errors: @question.errors.full_messages}
    end
  end

  def update
    @question.update(question_params)

    if !question_params[:best_answer_id].nil? && !@question.award.nil?
      @question.award.update(owner: @question.best_answer.author)
    end

    render json: @question
  end

  def destroy
    @question.destroy
    render json: { message: "Question was successfully deleted" }
  end

  private

  def set_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, :best_answer_id,
                                     links_attributes: [:id, :name, :url, :gist, :_destroy],
                                     award_attributes: [:id, :title, :image, :_destroy])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_question, only: [:show, :edit, :update, :destroy, :subscribe, :unsubscribe]

  after_action :publish_question, only: :create

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = user_signed_in? ? current_user.answers.new() : Answer.new
    @answer.links.build
    @best_answer = @question.best_answer
		@other_answers = @question.answers.where.not(id: @question.best_answer_id)
    @subscription = QuestionSubscription.find_by(user: current_user, question: @question)
  end

  def new
    @question = current_user.questions.new
    @question.links.build
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      @question.subscribers.push(current_user)
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)

    if !question_params[:best_answer_id].nil? && !@question.award.nil?
      @question.award.update(owner: @question.best_answer.author)
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Question was successfully deleted'
  end

  private

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/question',
        locals: { question: @question }
      )
    )
  end

  def set_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, :best_answer_id, files: [],
                                     links_attributes: [:id, :name, :url, :gist, :_destroy],
                                     award_attributes: [:id, :title, :image, :_destroy])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answers.html.slim
ol
  -resource.answers.each do |answer|
    -if !answer.new_record?
      li
        p= answer.body
        -if current_user&.author_of?(answer)
          =link_to 'Delete answer', answer_path(answer), method: :delete

app/views/questions/_question.html.slim
li.questions-list-item
  = link_to question.title, question_path(question), class: 'question-link'
  .question-description
    -if question.answers.count > 0
      span class='question-property answers-yes'
        | Answers: #{question.answers.count}
      span class='question-property last-answer-date'
        | Last answer: #{question.answers.last.created_at.to_datetime.to_formatted_s(:long_ordinal)}
      span.question-property
        | Best answer:
        -if question.best_answer
          span.tagged= ' tagged'
        -else
          span.not-tagged= ' not tagged'
    -else
      span class='question-property answers-no'
        | No answers

app/views/questions/_question_block.html.slim
h1= resourse.title
.question-body
  .question-main
    p.question-text= resourse.body
    .gists
      -resourse.links.gists.each do |gist|
        =javascript_include_tag gist.url+'.js'
        =link_to gist.name, gist.url, class: 'gist-link', data: { gist_id: gist.url.split("/").last }
    .question-extra
      -if !(resourse.links.not_gists).empty?
        ul.user-links
          -resourse.links.not_gists.each do |link|
            li
              =link_to link.name, link.url
              -if can?(:update, resourse)
                =link_to 'Delete link', link_path(link), method: :delete, remote: true
      -else
        p.no-links= 'No links'
      -if resourse.files.attached?
        ul.question-files
          -resourse.files.each do |file|
            li
              =link_to file.filename.to_s, url_for(file)
              -if can?(:update, resourse)
                =link_to 'Delete file', file_path(file), method: :delete, remote: true
      -else
        p.no-files= 'No files'
  .question-actions
    -if !resourse.award.nil?
      .award-container
        p.award-title= resourse.award.title
        -if !resourse.award.image.url.nil?
          .award-img-container
            =image_tag resourse.award.image.url, class: 'award-image'
    = render 'shared/rating', resource: resourse
    ul.question-links
      -if can?(:update, resourse)
        li.question-links-item
          =link_to 'Edit question', '#', class: 'edit-question-link question-links-link btn', data: { question_id: resourse.id }
          =form_with model: resourse, class: 'hidden edit-question-form', html: { id: "edit-question-#{resourse.id}" }, local: false do |f|
            .field
              =f.label :body, 'New question:'
              =f.text_area :body, rows: 5
            .field
              =f.label :files, class: 'files-label'
              =f.file_field :files, multiple: true, direct_upload: true
            #links
              = f.fields_for :links do |l|
                =render 'link_fields', :f => l
              .link-link
                =link_to_add_association 'add link', f, :links
            =f.submit 'Save', class: 'btn'
        li.question-links-item
          =link_to 'Delete question', question_path(resourse), class: 'btn question-links-link', method: :delete
      -if can?(:create, QuestionSubscription) && !current_user.subscriptions.include?(resourse)
        li.question-links-item
          =link_to 'Subscribe to question', question_question_subscriptions_path(resourse), class: 'btn question-links-link', method: :post
      -if can?(:destroy, subscription) && subscription
        li.question-links-item
          =link_to 'Unsubscribe from question', question_subscription_path(subscription), class: 'btn question-links-link', method: :delete

.question-editing-errors

-if !resourse.best_answer.nil?
  .best-answer
    h2.bets-answer-title = 'Best answer:'
    p.bets-answer-text = resourse.best_answer.body

app/views/questions/index.html.slim
h1.main-title= 'All Q&A questions'
ul.questions-list
  =render @questions

app/views/questions/new.html.slim
=render 'shared/errors', resource: @question

.new-question-form
  = form_with model: @question, local:true do |f|
    .field
      = f.label :title, 'New question'
      = f.text_field :title
    .field
      = f.label :body
      = f.text_area :body
    .field
      = f.label :files
      = f.file_field :files, multiple: true, direct_upload: true
    #links
      = f.fields_for :links do |l|
        =render 'link_fields', :f => l
      .link-link
        =link_to_add_association 'add link', f, :links
    #award
      = f.fields_for :award do |a|
        =render 'award_fields', :f => a
      .award-link
        =link_to_add_association 'add award', f, :award
    = f.submit 'Ask'

app/views/questions/show.html.slim
-cache @question do
  .question
    =render 'question_block', resourse: @question, subscription: @subscription

  .question-comments-container
    .question-comments-error
    ul.question-comments
      - @question.comments.each do |comment|
        li= comment.body

    =form_with url: create_comment_question_path(@question),
                                                 class: 'new-comment',
                                                 data: { type: :json },
                                                 local: false do |f|
      =f.label :body
      =f.text_area :body
      =f.submit 'Comment'

  h2= 'Answers'
  ol.answers
    -if !@question.answers.empty?
      =render @question.answers
    -else
      p= 'No answers yet'

  .answer-errors

  =form_with model: [@question, @answer], class: 'new-answer', local: false, data: { type: :json } do |f|
    .field
      =f.label :body, 'Your answer'
      =f.text_area :body
    .field
      =f.label :files
      =f.file_field :files, multiple: true, direct_upload: true
    #links
      = f.fields_for :links do |l|
        =render 'link_fields', :f => l
      .link-link
        =link_to_add_association 'add link', f, :links
    =f.submit 'Create'

app/views/questions/update.js.erb
$('.question-editing-errors').html('<%= render 'shared/errors', resource: @question %>');

<% if !@question.errors.present? %>
  $('.question').html('<%= j render @question %>');
  document.location.reload();
<% end %>