config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: 'questions#index'

  concern :votable do
    member do
      post :vote
      delete :unvote
    end
  end

  concern :commentable do
    member do
      post :create_comment
    end
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, shallow: true, except: :index, concerns: [:votable, :commentable]
    resources :question_subscriptions, only: [:create, :destroy], shallow: true
  end

post 'search', action: :create, controller: 'search'
get 'search', action: :show, controller: 'search'

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :comments, only: :destroy
  resources :users, only: :show

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, only: [:index, :show, :create, :update, :destroy], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected:"
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_header.html.slim
header.header
  div.page-container
    nav.navigation
      =link_to 'Q&A', root_path, class: 'logo'
      ul.navigation-list
        li.navigation-list-item
          -if can?(:create, Question)
            = link_to 'Ask!', new_question_path, class: 'navigation-link ask-link btn'
        -if user_signed_in?
          li.navigation-list-item
            = link_to 'My profile', user_path(current_user), class: 'navigation-link btn'
          li.navigation-list-item
            = link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'navigation-link btn'
        -else
          li.navigation-list-item
            = link_to 'Sign In', new_user_session_path, class: 'navigation-link btn'
          li.navigation-list-item
            = link_to 'Sign Up', new_user_registration_path, class: 'navigation-link btn'

app/views/shared/_rating.html.slim
div class="#{resource.class.to_s.downcase}-rating-wrapper"
  p class="#{resource.class.to_s.downcase}-rating-error"
  p class="#{resource.class.to_s.downcase}-rating"
    | Rating: #{resource.rating}
  -if cannot?(:update, resource)
    =link_to 'Vote for', polymorphic_path([:vote, resource], vote: { status: 1 }),
                         class: 'vote-link vote-for-link',
                         method: :post,
                         remote: true
    =link_to 'Vote against', polymorphic_path([:vote, resource], vote: { status: -1 }),
                             class: 'vote-link vote-against-link',
                             method: :post,
                             remote: true
    =link_to 'Change my vote', polymorphic_path([:unvote, resource]),
                               class: 'vote-link change-vote-link',
                               method: :delete,
                               remote: true

app/views/shared/_search.html.slim
.search-form
  = form_with url: search_url, local:true do |f|
    .field
      = f.label :query, 'Find'
      = f.text_field :query
    .field
      = f.radio_button :search_params, 'all'
      = f.label :search_params_all, 'All'
      = f.radio_button :search_params, 'question'
      = f.label :search_params_question, 'Question'
      = f.radio_button :search_params, 'answer'
      = f.label :search_params_answer, 'Answer'
      = f.radio_button :search_params, 'comment'
      = f.label :search_params_comment, 'Comment'
      = f.radio_button :search_params, 'user'
      = f.label :search_params_user, 'User'
    = f.submit 'Search'