config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: 'questions#index'

  concern :votable do
    member do
      post :vote
      delete :unvote
    end
  end

  concern :commentable do
    member do
      post :create_comment
    end
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, shallow: true, except: :index, concerns: [:votable, :commentable]
    resources :question_subscriptions, only: [:create, :destroy], shallow: true
  end

post 'search', action: :create, controller: 'search'
get 'search', action: :show, controller: 'search'

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :comments, only: :destroy
  resources :users, only: :show

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, only: [:index, :show, :create, :update, :destroy], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :question, touch: true
  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :body, presence: true

  after_create :send_creation_message

  def mark_as_best
		question.update(best_answer_id: self.id)
	end

  def best?
    question.best_answer == self
  end

  def send_creation_message
    AnswersMailer.created_answer(self).deliver_later
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!
  before_action :set_question, only: :create
  before_action :set_answer, only: [:update, :destroy]

  after_action :publish_answer, only: :create

  authorize_resource

  def create
    @answer = @question.answers.create(answer_params.merge(author: current_user))
  end

  def update
    @question = @answer.question
    @answer.update(answer_params)
  end

  def destroy
    @question = @answer.question
    @answer_id = @answer.id
    @answer.destroy
  end

  private

  def publish_answer
    return if @answer.errors.any?
    AnswersChannel.broadcast_to(
      @question,
      ApplicationController.render(
        partial: 'answers/public_answer',
        locals: { answer: @answer }
      )
    )
  end

  def set_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:id, :name, :url, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_question, only: [:new, :create]
  before_action :set_answer, only: [:edit, :update, :destroy]

  authorize_resource

  def index
    @question = Question.find(params[:question_id])
    render json: @question.answers
  end

  def show
    @answer = Answer.find(params[:id])
    render json: @answer
  end

  def create
    @answer = @question.answers.new(answer_params.merge(author: current_resource_owner))
    if @answer.save
      render json: @answer
    else
      render json: {errors: @answer.errors.full_messages}
    end
  end

  def update
    @answer.update(answer_params)
    render json: @answer
  end

  def destroy
    @answer.destroy
    render json: { message: "Answer was successfully deleted" }
  end

  private

  def set_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:id, :name, :url, :_destroy])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
-cache answer do
  -if !answer.new_record?
    li [id = "answer-#{answer.id}"]
      .answer-items
        p= answer.body
        .gists
          -answer.links.gists.each do |gist|
            =javascript_include_tag gist.url+'.js'
            =link_to gist.name, gist.url, class: 'gist-link', data: { gist_id: gist.url.split("/").last }
        -if !(answer.links.not_gists).empty?
          ul.user-links
            -answer.links.not_gists.each do |link|
              li
                =link_to link.name, link.url
                -if can?(:destroy, answer)
                  =link_to 'Delete link', link_path(link), method: :delete, remote: true
        -else
          p.no-links= 'No links'
        -if answer.files.attached?
          -answer.files.each do |file|
            =link_to file.filename.to_s, url_for(file)
            -if can?(:update, answer)
              =link_to 'Delete file', file_path(file), method: :delete, remote: true
        .answer-editing-errors
        -if can?(:update, answer.question)
          =link_to 'Mark as best', question_path(answer.question, question: { best_answer_id: answer.id }), class: 'best-link', method: :patch, remote: true
        -if can?(:update, answer)
          =link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
          =form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" }, local: false do |f|
            .field
              =f.label :body, 'New answer'
              =f.text_area :body
            .field
              =f.label :files
              =f.file_field :files, multiple: true, direct_upload: true
            #answer-links
              = f.fields_for :links do |l|
                =render 'link_fields', :f => l
              .link-link
                =link_to_add_association 'add link', f, :links
            =f.submit 'Save'
          =link_to 'Delete answer', answer_path(answer), class: 'delete-answer-link', method: :delete, remote: true
      = render 'shared/rating', resource: answer
      .answer-comments-container
        .answer-comments-error
        ul.answer-comments
          - answer.comments.each do |comment|
            li= comment.body
        =form_with url: create_comment_answer_path(answer), class: 'new-comment', local: false do |f|
          =f.label :body
          =f.text_area :body
          =f.submit 'Comment'

app/views/answers/_public_answer.html.slim
li [id = "answer-#{answer.id}"]
  .answer-items
    p= answer.body
    .gists
      -answer.links.gists.each do |gist|
        =javascript_include_tag gist.url+'.js'
        =link_to gist.name, gist.url, class: 'gist-link', data: { gist_id: gist.url.split("/").last }
    -if !(answer.links.not_gists).empty?
      ul.user-links
        -answer.links.not_gists.each do |link|
          li
            =link_to link.name, link.url
    -else
      p.no-links= 'No links'
    -if answer.files.attached?
      -answer.files.each do |file|
        =link_to file.filename.to_s, url_for(file)
  div class="answer-rating-wrapper"
    p class="answer-rating-error"
    p class="answer-rating"
      | Rating: #{answer.rating}
    =link_to 'Vote for', vote_answer_path(answer, vote: { status: 1 }),
                         class: 'vote-link vote-for-link',
                         method: :post,
                         remote: true
    =link_to 'Vote against', vote_answer_path(answer, vote: { status: -1 }),
                             class: 'vote-link vote-against-link',
                             method: :post,
                             remote: true
    =link_to 'Change my vote', unvote_answer_path(answer),
                               class: 'vote-link change-vote-link',
                               method: :delete,
                               remote: true
  =form_with url: create_comment_answer_path(answer), local: false do |f|
    =f.label :body
    =f.text_area :body
    =f.submit 'Comment'

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');
<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
  document.location.reload();
<% end %>

app/views/answers/destroy.js.erb
<% if !@answer.persisted? %>
  $('#answer-' + <%= @answer_id %>).remove();
  $('.question').html('<%= j render "questions/question_block", resourse: @question %>');
<% end %>

app/views/answers/update.js.erb
$('.answer-editing-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
  $('.answers').html('<%= j render @question.answers %>');
  $('.question').html('<%= j render @question %>');
  document.location.reload();
<% end %>